services:
  - type: web
    name: geocaching-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000 